/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iset.caminemoseltrayecto.visual;

import com.iset.caminemoseltrayecto.CaminemosElTrayecto;
import com.iset.caminemoseltrayecto.modelos.Admin;
import com.iset.caminemoseltrayecto.modelos.Alumno;
import com.iset.caminemoseltrayecto.modelos.Curso;
import com.iset.caminemoseltrayecto.modelos.Docente;
import java.util.ArrayList;

/**
 *
 * @author lucas
 */
public class AdminVisual extends javax.swing.JFrame {
    Admin admin;
    private Alumno [] alumnos;
    private Docente [] docentes;
    private Curso [] cursos;
    
    /**
     * Creates new form AdminVisual
     */
    public AdminVisual() {
        this.admin = admin;
        
        alumnos = new Alumno[((CaminemosElTrayecto.getAlumnos() == null)? 1 : CaminemosElTrayecto.getAlumnos().size() + 1)];
        alumnos[0] = null;

        if(alumnos.length >=2){
            int i = 1;
            for(Alumno a : CaminemosElTrayecto.getAlumnos()){
                alumnos[i] = a;// el i++ se puede agregar adentro de los corchetes teoricamente.
                i++;
            }
        }
        
        docentes = new Docente[((CaminemosElTrayecto.getDocentes() == null)? 1 : CaminemosElTrayecto.getDocentes().size() + 1)];
        docentes[0] = null;

        if(docentes.length >=2){
            int i = 1;
            for(Docente a : CaminemosElTrayecto.getDocentes()){
                docentes[i] = a;// el i++ se puede agregar adentro de los corchetes teoricamente.
                i++;
            }
        }
        
        cursos = new Curso[((CaminemosElTrayecto.getCursos() == null)? 1 : CaminemosElTrayecto.getCursos().size() + 1)];
        cursos[0] = null;

        if(cursos.length >=2){
            int i = 1;
            for(Curso a : CaminemosElTrayecto.getCursos()){
                cursos[i] = a;// el i++ se puede agregar adentro de los corchetes teoricamente.
                i++;
            }
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pSancionarUsuario = new javax.swing.JPanel();
        lTitleAdmin = new javax.swing.JLabel();
        lSubtituloSancionar = new javax.swing.JLabel();
        cbDocenteSancionar = new javax.swing.JComboBox<>();
        lDocenteSancionar = new javax.swing.JLabel();
        lAlumnosSancionar = new javax.swing.JLabel();
        cbAlumnoSancionar = new javax.swing.JComboBox<>();
        lUsuarioSeleccionado = new javax.swing.JLabel();
        tfUsuarioSeleccionadoSancionar = new javax.swing.JTextField();
        bSancionar = new javax.swing.JButton();
        pAgregarUsuario = new javax.swing.JPanel();
        lSubtituloNuevoUsuario = new javax.swing.JLabel();
        lAgregarDocente = new javax.swing.JLabel();
        lAgregarAlumno = new javax.swing.JLabel();
        lNombreUsuarioDocente = new javax.swing.JLabel();
        lNombreUsuarioAlumno = new javax.swing.JLabel();
        tfNombreUsuarioAlumno = new javax.swing.JTextField();
        lNombreAlumno = new javax.swing.JLabel();
        lNombreDocente = new javax.swing.JLabel();
        tfNombreUsuarioDocente = new javax.swing.JTextField();
        tfNombreDocente = new javax.swing.JTextField();
        tfNombreAlumno = new javax.swing.JTextField();
        lApellidoDocente = new javax.swing.JLabel();
        lApellidoAlumno = new javax.swing.JLabel();
        tfDNIDocente = new javax.swing.JTextField();
        tfApellidoAlumno = new javax.swing.JTextField();
        lTelefonoAlumno = new javax.swing.JLabel();
        lDNIDocente = new javax.swing.JLabel();
        tfDNIAlumno = new javax.swing.JTextField();
        tfApellidoDocente = new javax.swing.JTextField();
        bAddDocente = new javax.swing.JButton();
        bAddAlumno = new javax.swing.JButton();
        lDNIAlumno = new javax.swing.JLabel();
        tfTelefonoAlumno = new javax.swing.JTextField();
        pHabilitarCurso = new javax.swing.JPanel();
        lSubtituloHabilitarCurso = new javax.swing.JLabel();
        lDocenteHabilitar = new javax.swing.JLabel();
        cbDocenteHabilitar = new javax.swing.JComboBox<>();
        lCursoCreado = new javax.swing.JLabel();
        cbCursoCreado = new javax.swing.JComboBox<>();
        bHabilitar = new javax.swing.JButton();
        bCancelarNuevo = new javax.swing.JButton();
        pCancelarCurso = new javax.swing.JPanel();
        SubtituloSancion3 = new javax.swing.JLabel();
        lDocenteCancelar = new javax.swing.JLabel();
        cbDocenteCancelar = new javax.swing.JComboBox<>();
        lCursoCancelar = new javax.swing.JLabel();
        cbCursoCancelar = new javax.swing.JComboBox<>();
        bCancelar = new javax.swing.JButton();
        bCerrarSesionAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pSancionarUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lTitleAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lTitleAdmin.setText("Admin");

        lSubtituloSancionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lSubtituloSancionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lSubtituloSancionar.setText("Sancionar Usuario");

        cbDocenteSancionar.setModel(new javax.swing.DefaultComboBoxModel<>(alumnos));
        cbDocenteSancionar.setSelectedItem(alumnos[0]);

        lDocenteSancionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDocenteSancionar.setText("Docente");

        lAlumnosSancionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lAlumnosSancionar.setText("Alumno");

        cbAlumnoSancionar.setModel(new javax.swing.DefaultComboBoxModel<>(alumnos));
        cbDocenteSancionar.setSelectedItem(alumnos[0]);

        lUsuarioSeleccionado.setText("Usuario seleccionado:");

        tfUsuarioSeleccionadoSancionar.setText("UsuarioSeleccionado");
        tfUsuarioSeleccionadoSancionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsuarioSeleccionadoSancionarActionPerformed(evt);
            }
        });

        bSancionar.setText("Sancionar");
        bSancionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSancionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSancionarUsuarioLayout = new javax.swing.GroupLayout(pSancionarUsuario);
        pSancionarUsuario.setLayout(pSancionarUsuarioLayout);
        pSancionarUsuarioLayout.setHorizontalGroup(
            pSancionarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSancionarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitleAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pSancionarUsuarioLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pSancionarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lUsuarioSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lDocenteSancionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbDocenteSancionar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(pSancionarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lAlumnosSancionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfUsuarioSeleccionadoSancionar)
                    .addComponent(cbAlumnoSancionar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSancionarUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSancionar)
                .addGap(159, 159, 159))
            .addComponent(lSubtituloSancionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pSancionarUsuarioLayout.setVerticalGroup(
            pSancionarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSancionarUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lTitleAdmin)
                .addGap(23, 23, 23)
                .addComponent(lSubtituloSancionar)
                .addGap(18, 18, 18)
                .addGroup(pSancionarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDocenteSancionar)
                    .addComponent(lAlumnosSancionar))
                .addGap(18, 18, 18)
                .addGroup(pSancionarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDocenteSancionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAlumnoSancionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pSancionarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUsuarioSeleccionado)
                    .addComponent(tfUsuarioSeleccionadoSancionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(bSancionar)
                .addGap(430, 430, 430))
        );

        pAgregarUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lSubtituloNuevoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lSubtituloNuevoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lSubtituloNuevoUsuario.setText("Agregar Usuario Nuevo");

        lAgregarDocente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lAgregarDocente.setText("Agregar Docente");

        lAgregarAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lAgregarAlumno.setText("Agregar Alumno");

        lNombreUsuarioDocente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNombreUsuarioDocente.setText("Nombre de Usuario");

        lNombreUsuarioAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNombreUsuarioAlumno.setText("Nombre de Usuario");

        tfNombreUsuarioAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreUsuarioAlumnoActionPerformed(evt);
            }
        });

        lNombreAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNombreAlumno.setText("Nombre");

        lNombreDocente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNombreDocente.setText("Nombre");

        tfNombreUsuarioDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreUsuarioDocenteActionPerformed(evt);
            }
        });

        tfNombreDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreDocenteActionPerformed(evt);
            }
        });

        tfNombreAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreAlumnoActionPerformed(evt);
            }
        });

        lApellidoDocente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lApellidoDocente.setText("Apellido");

        lApellidoAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lApellidoAlumno.setText("Apellido");

        tfDNIDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDNIDocenteActionPerformed(evt);
            }
        });

        tfApellidoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidoAlumnoActionPerformed(evt);
            }
        });

        lTelefonoAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTelefonoAlumno.setText("Telefono");

        lDNIDocente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDNIDocente.setText("DNI");

        tfDNIAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDNIAlumnoActionPerformed(evt);
            }
        });

        tfApellidoDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidoDocenteActionPerformed(evt);
            }
        });

        bAddDocente.setText("Agregar Docente");
        bAddDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddDocenteActionPerformed(evt);
            }
        });

        bAddAlumno.setText("Agregar Alumno");
        bAddAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddAlumnoActionPerformed(evt);
            }
        });

        lDNIAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDNIAlumno.setText("DNI");

        tfTelefonoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefonoAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pAgregarUsuarioLayout = new javax.swing.GroupLayout(pAgregarUsuario);
        pAgregarUsuario.setLayout(pAgregarUsuarioLayout);
        pAgregarUsuarioLayout.setHorizontalGroup(
            pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAgregarUsuarioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lDNIDocente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lNombreUsuarioDocente, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addComponent(lAgregarDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lNombreDocente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfNombreUsuarioDocente)
                        .addComponent(tfNombreDocente)
                        .addComponent(lApellidoDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bAddDocente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfDNIDocente, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfApellidoDocente))
                .addGap(117, 117, 117)
                .addGroup(pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lAgregarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lNombreUsuarioAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNombreUsuarioAlumno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lNombreAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNombreAlumno)
                    .addComponent(lApellidoAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfApellidoAlumno)
                    .addComponent(lTelefonoAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfDNIAlumno)
                    .addComponent(lDNIAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfTelefonoAlumno)
                    .addComponent(bAddAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(pAgregarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lSubtituloNuevoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pAgregarUsuarioLayout.setVerticalGroup(
            pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAgregarUsuarioLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lSubtituloNuevoUsuario)
                .addGap(18, 18, 18)
                .addGroup(pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAgregarDocente)
                    .addComponent(lAgregarAlumno))
                .addGap(18, 18, 18)
                .addGroup(pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombreUsuarioDocente)
                    .addComponent(lNombreUsuarioAlumno))
                .addGap(18, 18, 18)
                .addGroup(pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombreUsuarioAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNombreUsuarioDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombreDocente)
                    .addComponent(lNombreAlumno))
                .addGap(18, 18, 18)
                .addGroup(pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lApellidoDocente)
                    .addComponent(lApellidoAlumno))
                .addGap(18, 18, 18)
                .addGroup(pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfApellidoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDNIDocente)
                    .addComponent(lDNIAlumno))
                .addGap(18, 18, 18)
                .addGroup(pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDNIDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDNIAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTelefonoAlumno)
                    .addComponent(bAddDocente))
                .addGap(15, 15, 15)
                .addComponent(tfTelefonoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bAddAlumno)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pHabilitarCurso.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lSubtituloHabilitarCurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lSubtituloHabilitarCurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lSubtituloHabilitarCurso.setText("Habilitar Curso");

        lDocenteHabilitar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDocenteHabilitar.setText("Docente");

        cbDocenteHabilitar.setModel(new javax.swing.DefaultComboBoxModel<>(alumnos));
        cbDocenteSancionar.setSelectedItem(alumnos[0]);

        lCursoCreado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCursoCreado.setText("Curso creado");

        cbCursoCreado.setModel(new javax.swing.DefaultComboBoxModel<>(alumnos));
        cbDocenteSancionar.setSelectedItem(alumnos[0]);

        bHabilitar.setText("Habilitar");
        bHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHabilitarActionPerformed(evt);
            }
        });

        bCancelarNuevo.setText("Cancelar");
        bCancelarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pHabilitarCursoLayout = new javax.swing.GroupLayout(pHabilitarCurso);
        pHabilitarCurso.setLayout(pHabilitarCursoLayout);
        pHabilitarCursoLayout.setHorizontalGroup(
            pHabilitarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pHabilitarCursoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pHabilitarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lDocenteHabilitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lCursoCreado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pHabilitarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDocenteHabilitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCursoCreado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addGroup(pHabilitarCursoLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(bHabilitar)
                .addGap(87, 87, 87)
                .addComponent(bCancelarNuevo)
                .addContainerGap(81, Short.MAX_VALUE))
            .addComponent(lSubtituloHabilitarCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pHabilitarCursoLayout.setVerticalGroup(
            pHabilitarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHabilitarCursoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lSubtituloHabilitarCurso)
                .addGap(18, 18, 18)
                .addGroup(pHabilitarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDocenteHabilitar)
                    .addComponent(cbDocenteHabilitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pHabilitarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCursoCreado)
                    .addComponent(cbCursoCreado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pHabilitarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bHabilitar)
                    .addComponent(bCancelarNuevo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pCancelarCurso.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SubtituloSancion3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SubtituloSancion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubtituloSancion3.setText("Cancelar Curso");

        lDocenteCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDocenteCancelar.setText("Docente");

        cbDocenteCancelar.setModel(new javax.swing.DefaultComboBoxModel<>(alumnos));
        cbDocenteSancionar.setSelectedItem(alumnos[0]);

        lCursoCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCursoCancelar.setText("Curso");

        cbCursoCancelar.setModel(new javax.swing.DefaultComboBoxModel<>(alumnos));
        cbDocenteSancionar.setSelectedItem(alumnos[0]);

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bCerrarSesionAdmin.setText("Cerrar Sesion");
        bCerrarSesionAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarSesionAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCancelarCursoLayout = new javax.swing.GroupLayout(pCancelarCurso);
        pCancelarCurso.setLayout(pCancelarCursoLayout);
        pCancelarCursoLayout.setHorizontalGroup(
            pCancelarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCancelarCursoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pCancelarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lDocenteCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lCursoCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pCancelarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDocenteCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCursoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addGroup(pCancelarCursoLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(bCancelar)
                .addContainerGap(162, Short.MAX_VALUE))
            .addComponent(SubtituloSancion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCancelarCursoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bCerrarSesionAdmin)
                .addContainerGap())
        );
        pCancelarCursoLayout.setVerticalGroup(
            pCancelarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCancelarCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bCerrarSesionAdmin)
                .addGap(20, 20, 20)
                .addComponent(SubtituloSancion3)
                .addGap(18, 18, 18)
                .addGroup(pCancelarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDocenteCancelar)
                    .addComponent(cbDocenteCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pCancelarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCursoCancelar)
                    .addComponent(cbCursoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bCancelar)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pSancionarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pHabilitarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pCancelarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pCancelarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pHabilitarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pSancionarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pAgregarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsuarioSeleccionadoSancionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsuarioSeleccionadoSancionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsuarioSeleccionadoSancionarActionPerformed

    private void bSancionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSancionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSancionarActionPerformed

    private void tfNombreUsuarioAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreUsuarioAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreUsuarioAlumnoActionPerformed

    private void tfNombreUsuarioDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreUsuarioDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreUsuarioDocenteActionPerformed

    private void tfNombreDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreDocenteActionPerformed

    private void tfNombreAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreAlumnoActionPerformed

    private void tfDNIDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDNIDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDNIDocenteActionPerformed

    private void tfApellidoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidoAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellidoAlumnoActionPerformed

    private void tfDNIAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDNIAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDNIAlumnoActionPerformed

    private void tfApellidoDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidoDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellidoDocenteActionPerformed

    private void bAddDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddDocenteActionPerformed
        if(evt.getSource() == bAddDocente){
            admin.addDocente(new Docente(tfNombreUsuarioDocente.getText(), tfDNIDocente.getText(), tfNombreDocente.getText(), tfApellidoDocente.getText(), tfDNIDocente.getText()));
        }
    }//GEN-LAST:event_bAddDocenteActionPerformed

    private void bAddAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddAlumnoActionPerformed
        if(evt.getSource() == bAddAlumno){
            admin.addAlumno(new Alumno(tfNombreUsuarioAlumno.getText(), tfDNIAlumno.getText(), tfNombreAlumno.getText(), tfApellidoAlumno.getText(), tfDNIAlumno.getText(), tfTelefonoAlumno.getText()));
        }
    }//GEN-LAST:event_bAddAlumnoActionPerformed

    private void bHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHabilitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bHabilitarActionPerformed

    private void bCancelarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCancelarNuevoActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCancelarActionPerformed

    private void tfTelefonoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefonoAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefonoAlumnoActionPerformed

    private void bCerrarSesionAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarSesionAdminActionPerformed
        if(evt.getSource() == bCerrarSesionAdmin){
            this.setVisible(false);
            CaminemosElTrayecto.goLogIn();
        }
    }//GEN-LAST:event_bCerrarSesionAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SubtituloSancion3;
    private javax.swing.JButton bAddAlumno;
    private javax.swing.JButton bAddDocente;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bCancelarNuevo;
    private javax.swing.JButton bCerrarSesionAdmin;
    private javax.swing.JButton bHabilitar;
    private javax.swing.JButton bSancionar;
    private javax.swing.JComboBox<Alumno> cbAlumnoSancionar;
    private javax.swing.JComboBox<Alumno> cbCursoCancelar;
    private javax.swing.JComboBox<Alumno> cbCursoCreado;
    private javax.swing.JComboBox<Alumno> cbDocenteCancelar;
    private javax.swing.JComboBox<Alumno> cbDocenteHabilitar;
    private javax.swing.JComboBox<Alumno> cbDocenteSancionar;
    private javax.swing.JLabel lAgregarAlumno;
    private javax.swing.JLabel lAgregarDocente;
    private javax.swing.JLabel lAlumnosSancionar;
    private javax.swing.JLabel lApellidoAlumno;
    private javax.swing.JLabel lApellidoDocente;
    private javax.swing.JLabel lCursoCancelar;
    private javax.swing.JLabel lCursoCreado;
    private javax.swing.JLabel lDNIAlumno;
    private javax.swing.JLabel lDNIDocente;
    private javax.swing.JLabel lDocenteCancelar;
    private javax.swing.JLabel lDocenteHabilitar;
    private javax.swing.JLabel lDocenteSancionar;
    private javax.swing.JLabel lNombreAlumno;
    private javax.swing.JLabel lNombreDocente;
    private javax.swing.JLabel lNombreUsuarioAlumno;
    private javax.swing.JLabel lNombreUsuarioDocente;
    private javax.swing.JLabel lSubtituloHabilitarCurso;
    private javax.swing.JLabel lSubtituloNuevoUsuario;
    private javax.swing.JLabel lSubtituloSancionar;
    private javax.swing.JLabel lTelefonoAlumno;
    private javax.swing.JLabel lTitleAdmin;
    private javax.swing.JLabel lUsuarioSeleccionado;
    private javax.swing.JPanel pAgregarUsuario;
    private javax.swing.JPanel pCancelarCurso;
    private javax.swing.JPanel pHabilitarCurso;
    private javax.swing.JPanel pSancionarUsuario;
    private javax.swing.JTextField tfApellidoAlumno;
    private javax.swing.JTextField tfApellidoDocente;
    private javax.swing.JTextField tfDNIAlumno;
    private javax.swing.JTextField tfDNIDocente;
    private javax.swing.JTextField tfNombreAlumno;
    private javax.swing.JTextField tfNombreDocente;
    private javax.swing.JTextField tfNombreUsuarioAlumno;
    private javax.swing.JTextField tfNombreUsuarioDocente;
    private javax.swing.JTextField tfTelefonoAlumno;
    private javax.swing.JTextField tfUsuarioSeleccionadoSancionar;
    // End of variables declaration//GEN-END:variables
}
